Makefile, exec/exec.go, exec/exec_test.go, exec/fixture/infinite.sh
`dcos-go/exec` is a os/exec wrapper. It implements io.Reader and can be used to read both STDOUT and STDERR. It also adds timeout.
=> add lib `exec`

.gitignore, Makefile, README.md, scripts/test.sh
This PR improves our test scripts to include things like goimports,
gofmt, and govet. It also outputs test reports and code coverage results
in a way that Jenkins can understand (JUnit and Cobertura,
respectively), allowing us to track our testing over time.
This PR also adds the build status for the `master` branch to README.md.
=> Improve test scripts and Jenkins-friendly output

store/store.go, store/store_test.go
This commit adds the ability to return a map of objects from `store`
based on a regular expression. The intended usage is in dcos-metrics,
so that it will be possible to query the store with something like:
```go
s.GetByRegex("dcos.metrics.containers.*")
```
=> Add ability to search store by regexp

dcos/nodeutil/util.go, dcos/nodeutil/util_test.go
this is non-breaking change that adds ability for user to pass custom request
headers to `MesosID` function.
This will be used for authorization. Instead of system account, we will make
a request on user's behalf. In order to do so, we need to be able to pass
Authorization header to http request.
=> dcos/nodeutil: add headers to mesos-id request

dcos/constants.go, dcos/nodeutil/cmd/example/main_jwt.go, dcos/nodeutil/options.go, dcos/nodeutil/util.go, dcos/nodeutil/util_test.go
detecting a node's role in runtime is not very trivial task and leads to
errors and bugs in software, since we cannot predict users environment.
A source of truth for node's role is gen library. Every service which is using
this package must be aware of the node's role from it's config file, which
in turn, is generated by dcos-config.yaml. This approach will eliminate the
need of hardcoding files which describe the roles and will make the library
robust.
related issues: https://mesosphere.atlassian.net/browse/DCOS-11680
=> dcos/nodeutil: remove .Role() method

dcos/nodeutil/util.go, exec/exec.go, exec/exec_test.go
remove the functional parameters, this is redundant in this case and let the
user ability to pass a context to control the cancellation and timeouts.
=> exec: refactor

exec/exec.go, exec/exec_test.go
This removes exec.Output() and adds FullOutput() and
SimpleFullOutput(). FullOutput() allows the caller to run a customized
Cmd struct instead of a string array. SimpleFullOutput() replaces
Output().
This also adds two convenience functions that can create a Cmd from a
string array: Command() and CommandContext()
See https://github.com/dcos/dcos-diagnostics/pull/8.
=> Add FullOutput() and SimpleFullOutput()

exec/exec.go
The usage changed after some refactoring (https://github.com/dcos/dcos-go/commit/52d35f5a9660aff52a3cd0fcb933d059f769b5e5).
=> exec: update usage example

dcos/http/transport/README.md, dcos/http/transport/option.go, dcos/http/transport/roundtripper.go, scripts/test.sh
Dependencies of this library had to pin jwt-go to an old version. This is not necessary anymore.
- Dependencies now need to move from jwt-go 2.6.0 to 3.1.0
=> http/transport: update code to jwt-go 3.1.0

dcos/nodeutil/README.md, dcos/nodeutil/fixture/state.json, dcos/nodeutil/mesos.go, dcos/nodeutil/mesos_test.go, dcos/nodeutil/util.go, dcos/nodeutil/util_test.go
Both `dcos-metrics` and `dcos-log` need a way to find metadata associated with a task.
User should only know the task ID, the rest of metadata must be looked up in state.json
- [] [optional list]
Adding a new method should not affect any existing libraries.
=> dcos/nodeutil: add TaskCanonicalID

dcos/http/transport/option.go, dcos/http/transport/roundtripper.go, scripts/test.sh
- [] Updated [README.md](README.md)?
1. go-jose v2 is widely used and actively maintained
2. I need to use other functionality from go-jose such as jwk. We probably don't want to always include two libraries
=> http/transport: use more maintained gopkg.in/square/go-jose.v2

dcos/nodeutil/fixture/state.json, dcos/nodeutil/mesos.go, dcos/nodeutil/util.go, dcos/nodeutil/util_test.go
in dcos-log v2 the user will want to access the logs for the completed tasks.
N/A
N/A
=> make possible to get CanonicalID for completed tasks

dcos/nodeutil/fixture/state.json, dcos/nodeutil/mesos.go, dcos/nodeutil/util.go, dcos/nodeutil/util_test.go
Add finding tasks in `completed_frameworks`.
[DCOS-20083](https://jira.mesosphere.com/browse/DCOS-20083)
Mesos stores completed tasks in completed_frameworks field. This change adds support for it.
- [] [optional list]
`dcos-log` is the only component affected by this change.
=> add support to find tasks in completed frameworks

Dockerfile, Gopkg.lock, Makefile, scripts/test.sh
Now that the project is using dep, the test script no longer needs to use govendor (hopefully)
JIRA: https://jira.mesosphere.com/browse/DCOS-21365
Also, some general housekeeping was done as a part of this PR.
JIRA: https://jira.mesosphere.com/browse/DCOS-21365
The idea is to try and standardize the build mechanics across the cluster ops projects.
This should have no change re: usage.
=> Update Makefile and test script

elector/connector.go, elector/connector_existing.go, elector/connector_new.go, elector/elector.go, elector/elector_test.go, zkstore/validate.go
- [] ~80% unit test coverage?
* https://jira.mesosphere.com/browse/DSS_EE-101
Downstream projects that implement the `elector.Connector` API will need updates because the interface was made more generic.
=> elector: API tweaks and deadlock fix

zkstore/README.md, zkstore/store.go, zkstore/store_test.go, zkstore/validate.go
When using the zkstore API it is sometimes useful to know that a given Item is being created for the first time. Currently similar functionality is available by passing a specific Version to the Put function which returns ErrVersionConflict if the specified version is not the latest one. However, this is only possible when the Item already exists in the store, not when it is first created.
This PR extends the logic around ErrVersionConflict on Put by allowing the caller to explicitly specify Version(-1) to signal that an ErrVersionConflict error should be returned if the Item already exists. The standard way to signal "overwrite the latest version, irrespective of its previous value" is to simply not specify the `Item.Ident.Version` field.
- zkstore: allow explicit create by passing …
=> zkstore: allow explicit create by passing Version(-1) to Put

dcos/constants.go, dcos/dns_records.go, dcos/ports.go
- [] ~80% unit test coverage?
- [] Updated [README.md](README.md)?
Multiple DC/OS checks access the DC/OS internal HTTP servers on those pre-defined ports.
Also having multiple projects using those ports, they should not be re-defined in every repository.
Having a single location for the port constants makes it easier to maintain them.
This should be the default location that DC/OS ports are referenced from so that in case of a change
it only needs to be changed in one location.
=> Add missing DC/OS internal constants

dcos/ports.go
- [] ~80% unit test coverage?
- [] Updated [README.md](README.md)?
Adding missing DC/OS ports so that they only reside in one place.
This is part of the attempt to make this the central Go library for interacting with DC/OS.
=> Add Adminrouter HTTP port constant

.gitattributes, zkstore/store_test.go
Some of the tests that run on Jenkins Windows Slaves fail:
- The diff from gofmt command throws errors because of different OS line endings 
-> Add .gitattributes file
- The docker image used for zkstore tests is a Linux docker image 
-> Skip those tests on Windows
Some of the zookeeper tests that are using a linux docker image will not run on Windows
=> Fix Windows unittests

dcos/nodeutil/util_test.go, scripts/test.ps1
Re-ordered go imports to fix test errors
Fixed golint import path error introduced with:
https://github.com/golang/lint/commit/9a272034dedb2a3ed05231d5604ce17fb40f0e58
=> Fix go imports

dcos/http/transport/README.md, dcos/http/transport/option.go, dcos/http/transport/roundtripper.go, dcos/http/transport/roundtripper_test.go
note: windows build will fail until https://jira.mesosphere.com/browse/DCOS-44309 is resolved
- [] ~80% unit test coverage?
https://jira.mesosphere.com/browse/DCOS_OSS-4168
It would be valuable to send a `User-Agent` with requests to correlate them with the originator. The `User-Agent` defaults to `dcos-go` if one is not passed through using [`OptionUserAgent`](https://github.com/dcos/dcos-go/compare/gracedo/add_user_agent_header?expand=1#diff-15f81910753ae4f24ad4f94b11f3bde1R115)
A `User-Agent` header will be sent along with all requests going through this transport.
=> Add User-Agent header to requests
